export const operator = {
  brandName: "mein-vermieterrechtsschutz24",
  name: "Agapios Papadakis",
  qualification: "Hauptgeschäftsstellenleiter ARAG Versicherungen",
  businessName: "ARAG Hauptgeschäftsstelle Augsburg",
  street: "Wankelstraße 2",
  city: "86356 Neusäß",
  contactOfficeStreet: "Wankelstraße 2",
  contactOfficeCity: "86356 Neusäß",
  phoneDisplay: "0821 509280",
  phoneHref: "+49821509280",
  email: "info@rechtsschutzpartner24.de",
  directEmail: "Agapios.Papadakis@arag-partner.de",
  registerNumber: "D-05V5-SZ9YK-16",
  profileUrl: "https://www.arag-partner.de/gst-augsburg/",
} as const;
